services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend/database.sqlite3:/app/db.sqlite3
      - ./backend/media:/app/media
    env_file:
      - .env.prod
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-https://epcchronicles.com/api}
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./backend/media:/usr/share/nginx/html/media
    env_file:
      - .env.prod
    restart: always

volumes:
  db_data:
