# Generated by Django 6.0.2 on 2026-04-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_group',
            field=models.CharField(blank=True, db_index=True, help_text='Common name for a group of issues (e.g. Day 1 Dispatches)', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='event_category',
            field=models.CharField(choices=[('Oasis', 'Oasis'), ('Apogee', 'Apogee'), ('BOSM', 'BOSM'), ('Other', 'Other')], db_index=True, default='Apogee', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['issue_group'], name='news_issue_issue_g_12d892_idx'),
        ),
    ]
