# Generated by Django 6.0.2 on 2026-04-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_news_articl_publish_385002_idx_news_articl_publish_2bbbd4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_hero',
            field=models.BooleanField(db_index=True, default=False, help_text='Set to true to feature this article as a hero. Only one article can be a hero at a time.'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_hero'], name='news_articl_is_hero_0bf190_idx'),
        ),
    ]
